# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RadioRecordCli < Formula
  desc "Terminal radio player for Radio Record stations"
  homepage "https://github.com/isalikov/radio-record-cli"
  version "1.0.0"
  license "MIT"

  depends_on "mpv" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isalikov/radio-record-cli/releases/download/v1.0.0/radio-record-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "c950c52e41cf89deef7dae36cc08ff5efadfcee3a13f38392765ff17a458bec1"

      def install
        bin.install "radio-record"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isalikov/radio-record-cli/releases/download/v1.0.0/radio-record-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "7d838097b381f38bd7d94b606c8c78736c00fac79cf71b61abe27932ab95d782"

      def install
        bin.install "radio-record"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isalikov/radio-record-cli/releases/download/v1.0.0/radio-record-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "40b8a44d67b296b71ca4ff2ffb4bca6790952a45e48beb0e8c1beaa1a8833d3b"
      def install
        bin.install "radio-record"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isalikov/radio-record-cli/releases/download/v1.0.0/radio-record-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "4b4da751af5c4a58d22de701a10cb47a04a18de7446db673bb8b3ba52fcf2b80"
      def install
        bin.install "radio-record"
      end
    end
  end

  test do
    system "#{bin}/radio-record", "--version"
  end
end
