# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RadioRecordCli < Formula
  desc "Terminal radio player for Radio Record stations"
  homepage "https://github.com/isalikov/radio-record-cli"
  version "1.1.1"
  license "MIT"

  depends_on "mpv" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isalikov/radio-record-cli/releases/download/v1.1.1/radio-record-cli_1.1.1_darwin_amd64.tar.gz"
      sha256 "93d20f784ad5e668a51f46e9a7784f40581a87c3d6736c38d46c0403c61c8a11"

      def install
        bin.install "radio-record"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isalikov/radio-record-cli/releases/download/v1.1.1/radio-record-cli_1.1.1_darwin_arm64.tar.gz"
      sha256 "407e788c5eceb2368abf9a87a4230d2f4fe99413819f094eba829eeaa6e14579"

      def install
        bin.install "radio-record"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isalikov/radio-record-cli/releases/download/v1.1.1/radio-record-cli_1.1.1_linux_amd64.tar.gz"
      sha256 "397acda7f06ec4db57e2766f9e4087ec2269926fe03fec6d98c3297829a11e4e"
      def install
        bin.install "radio-record"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isalikov/radio-record-cli/releases/download/v1.1.1/radio-record-cli_1.1.1_linux_arm64.tar.gz"
      sha256 "0b05c6fcfba897c618ea49fa97a87a573a5e4cc70979a3572349a1df414e392c"
      def install
        bin.install "radio-record"
      end
    end
  end

  test do
    system "#{bin}/radio-record", "--version"
  end
end
